spring:
  application:
    name: gateway
#    配置网关路由
  cloud:
    gateway:
      routes:
        - id: get-name
          uri: http://localhost:7000
          predicates:
          - Path=/getName
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 6000